---
title: "Day 3 Postmortem"
author: "Erik Westlund"
date: "2025-06-12"
---

## Video Recording

The video recording [can be viewed by clicking here](https://jhjhm.zoom.us/rec/share/_kcjdJzRpr-QhStcLFNbbWBUVekOb2HZtNQLLdWSwNPxTyuSzbxpqp2ywIcfS3zh.6hZJ1hWATbzQAHp_?startTime=1749733850000).

The password has been shared via email and CoursePlus.

## Support on Zoom

If you  have any questions or need any help, please reach out to me via email. If you are a JHU student, faculty, or staff memmber, you can reach me on Teams.

## Interaction Effects

I have updated the [applications_6_visualizing_correlations_and_models.qmd](https://erikwestlund.github.io/data-viz-summer-25/examples/applications_6_visualizing_correlations_and_models.html) example to include a section on interaction effects. There are two examples:

* A simple categorical by continuous interaction
* A more complex scenario with a three-way interaction, one categorical and two continuous variables.

I use the `emmeans` package with `ggplot2` to explore the interaction effects and make sense of them in a way that is very challenging without visualization.

## Shiny Dashboard Example

I have added a shiny example to the `examples` directory. This takes the simulated maternal health data and creates a shiny app that allows you to explore the data.  You can run it in RStudio by opening the `examples/shiny_example.R` file and clicking the "Run App" button.

I opted not to include this in the daily instruction because of time constraints.

## Problem Sets/Final Project

Please reach out to me if you need an extension.